config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'chat_rooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets do
    resources :ratings, only: [:new, :create]
  end
  resources :matches, only: [:index, :show]

  resources :chat_rooms, only: [:show] do
    resources :messages, only: [:create]
  end

  get 'my_page', to: 'users#my_page', as: :my_page
  get 'friends', to: 'users#friends', as: :friends
  get 'chats', to: 'users#chats', as: :chats
  get 'map', to: 'users#map', as: :map
  get 'users/:id/request', to: 'users#friend_request', as: :request
  get 'users/:id/accept', to: 'users#friend_accept', as: :accept
  get 'users/:id/reject', to: 'users#friend_reject', as: :reject
  get 'users/:id/accept_show', to: 'users#friend_accept_show', as: :accept_show
  # post 'chat_rooms/:chat_room_id/messages', to: 'messages#create', as: :chat_room_messages
  # get 'chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room

  get 'users/:id/remove', to: 'users#friend_remove', as: :remove

  mount ActionCable.server => "/cable"

  resources :collections do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :ratings
  validates :name, :gender, :breed, :age, presence: true
  validates :age, numericality: {only_integer: true}
  validates :description, length: {maximum: 120}
  has_many_attached :photos
  #acts_as_taggable_on :personalities, :preferences
  GENDER = ["Male", "Female"]
  PERSONALITY = ["Shy", "Active", "Confident", "Independent", "Happy", "Adaptable"]
  PREFERNECE = ["Indoor", "Active", "Outdoor", "Quiet", "Adaptable","Dogpark", "Running", "Relaxing", "Independent", "Likes Dog Restaurant"]

  def compatibilty(pet_second)
    number = personality_list.count do |pers|
      pet_second.personality_list.include?(pers)
    end
    return 0 if personality_list.count.zero?

    percentage = number / personality_list.count.to_f * 100
    percentage > 100 ? 100 : percentage.round(1)
    # if personality_list && current_user.pet.preference_list include?
    #   return 1
    # elsif current_user.pet.personality_list || current_user.pet.preference_list include?
    #   return 0.5
    # else
    #   return 0
    # end

  end

  def rating
    return nil if ratings.empty?

    sum = ratings.sum(&:stars)
    (sum.to_f / ratings.length).round
  end


end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :delete]
  #respond_to :html
  #respond_to :js

  def index
      @pets = Pet.where.not(user: current_user.excluded_friends, id: current_user.pet).order('name ASC').limit(1)
    # byebug
    # @pets = Pet.where.not(user: current_user.excluded_friends, id: current_user.pet).first(5)
    # @pets = Pet.all
    # respond_with(@pets)
  end

  def show
    #     @rating.user = @pet.user
    # @rating.pet = @pet
    # pet_first_personality(current_user.pet.personality_list)
    # pet_second_personality(current_user.pet.personality_list)
    # pet_first_preference(current_user.pet.preference_list)
    # pet_second_preference(current_user.pet.preference_list)
  end
  # @related_pets = @pet.find_related_personalities

  def new
    @pet = Pet.new
    # @user = User.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to my_page_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to my_page_path
    else
      render :edit
    end
  end

  def delete
    @pet.delete
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :gender, :age, :breed, :description, photos: [], preference_list: [], personality_list: [] )
  end

end

app/views/pets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 offset-sm-4" id="pet-dog">
      <div class="form-pet">
        <%= simple_form_for @pet do |f| %>
          <%= f.input :name, label: "Please add you pet name", hint: "Jack, Baily, Max" %>
          <%= f.input :gender, label: "Please add you dog gender", collection: Pet::GENDER %>
          <%= f.input :age, label: "Please add you pet age", input_html: { type: 'number' } %>
          <%= f.input :breed, label: "Please add you pet breed", hint: "Husky, Pomerania, Buldog" %>
          <%= f.input :description, label: "Please add any aditional information", hint: "my dog is allergic to peanuts", input_html: { maxlength: 120 }%>
          <%= f.input :photos, as: :file, label: false, input_html: { multiple: true } %>
          <%= f.input :personality_list, as: :check_boxes, collection: ["Shy", "Active", "Confident", "Independent", "Happy", "Adaptable"] %>
          <%= f.input :preference_list, as: :check_boxes, collection: ["Indoor", "Active", "Outdoor", "Quiet", "Adaptable","Dogpark", "Running", "Relaxing", "Independent", "Likes Dog Restaurant"] %>
          <%#= f.input :personality_list, label: "Add tags", hint: "Add your tags, separated by commas" %>
          <%#= f.input :preference_list, label: "Add tags", hint: "Add your tags, separated by commas" %>
          <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render "pets/form" %>

app/views/pets/index.html.erb
<% if current_user.pet %>
  <div class="cards-category-index">
    <div class="swiper-container animated zoomIn faster">
      <div class="swiper-wrapper">
        <%@pets.each do |pet|%>
          <div class="swiper-slide" >
            <div class="card-product-picture">
              <div class="photo-slideshow">
                <div class="swiper-wrapper">
                  <% if pet.photos.attached? %>
                    <%  pet.photos.each do |photo|%>
                      <div class="swiper-slide" >
                        <%= cl_image_tag(photo.key, class: "picture-dog", width: 1000, height: 1000, crop: :fill) %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="card-product-value">
                <p><%= current_user.pet.compatibilty(pet) %>%</p>
              </div>
              <div class="card-product-picture-info-name">
                <p> <%= pet.name %> </p>
              </div>
              <div class="dog-rating">
                <% if pet.rating.blank? %>
                  <p><%= pet.rating %>  </p>
                <% else %>
                  <p><% (pet.rating).times do %>
                      <i class="fas fa-bone"></i>
                    <% end %>
                    <% (5 - pet.rating).times do %>
                      <i class="fas fa-bone boni"></i>
                    <% end %></p>
                  <span>(<%= pet.ratings.count%>)</span>
                <% end %>
              </div>
              <!-- <div class="button-expand btn btn-primary" style="position: absolute; bottom: 10px; right: 10px;">Expand</div> -->
              <%= link_to "#", class: "button-expand", id: "button-index-expand" do %>
                <i class="fas fa-info-circle"></i>
              <% end %>
            </div>
            <div class="card-information-dog">
              <div class="card-information-dog-persnpref">
                <div class="card-information-dog-namenbreed">
                  <p><strong><%= pet.breed %></strong></p>
                  <p><strong><%= pet.age %></strong>
                    <% if pet.gender == "male" %>
                      <i class="fas fa-mars"></i>
                    <% else %>
                      <i class="fas fa-venus"></i>
                    <% end %>
                  </p>
                </div>
                <div class="card-information-dog-personalities">
                  <p><strong>Personality</strong></p>
                  <p><%= pet.personality_list %></p>
                </div>
                <div class="card-information-dog-preferences">
                  <p><strong>Preferences</strong></p>
                  <p><%= pet.preference_list %></p>
                </div>
              </div>
              <div class="card-information-dog-description">
                <p><strong>Description</strong></p>
                <p> <%= pet.description %>  </p>
              </div>
              <div class="show-all-reviews">
                <h3>Reviews and Ratings</h3>
                <% if pet.ratings.any? %>
                  <div class="first-reviews">
                    <% pet.ratings.first(5).each do |rating| %>
                      <p class="first-reviews-p"><%= rating.comments %></p>
                      <p>
                        <% (rating.stars).times do %>
                          <i class="fas fa-bone"></i>
                        <% end %>
                        <% (5 - rating.stars).times do %>
                          <i class="fas fa-bone boni"></i>
                        <% end %>
                      </p>
                    <% end %>
                    <!-- </div> -->
                  </div>
                  <div class="show-all-button button-chat" id="button-chat-margin">
                    Show all reviews
                  </div>
                  <div class="remaining-reviews hidden">
                    <% pet.ratings.last(pet.ratings.count-5).each do |rating| %>
                      <p class="remaining-reviwes-p"><%= rating.comments %></p>
                      <p><% (rating.stars).times do %>
                          <i class="fas fa-bone"></i>
                        <% end %>
                        <% (5 - rating.stars).times do %>
                          <i class="fas fa-bone boni"></i>
                        <% end %>
                      </p>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="swiper-slide"></div>
      </div>
      <div class="swiper-pagination"></div>
      <!--       <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div> -->
    </div>
  </div>
</div>
<!-- <button id="sweet-alert-matched" class="btn btn-primary">Matched</button> -->
<button id="sweet-alert-matched" class="btn-transparent">Matched</button>
<div class="btn-group d-flex justify-content-between">
  <button type="button" id="btn-nope" class="btn-transparent"><img src="https://res.cloudinary.com/diyszwqhl/image/upload/v1583922785/nope_btn_qz1lsu.png"/><%= link_to "Nope", reject_path(@pets.first.user),remote: true %></button>
  <button type="button" class="btn-transparent" id="btn-like"><img src="https://res.cloudinary.com/diyszwqhl/image/upload/v1583922798/like_btn_jnyyno.png"/><%= link_to "Like", accept_path(@pets.first.user),remote: true %></button>
</div>
  <button type="button" class="btn-transparent" id="btn-my-friend"><%= link_to "friend", friends_path %></button>

<% else %>
  <%= render 'shared/create_pet' %>
<% end %>
<script>
  var mySwiper = new Swiper('.swiper-container', {
    init: false,
    speed: 700,
    loop: true,
    spaceBetween: 100,
    autoHeight: true, //enable auto height
    // freeModeMomentum: true,
    touchRatio: 1.1,
    on: {

      init () {
        console.log('swiper initialized');
      },
      slideChange () {
        if ( mySwiper.activeIndex > mySwiper.previousIndex ) {
          console.log('swipe to the left');
          window.location.href = '<%= reject_path(@pets.first.user) %>';
        } else {
          console.log('swipe to the right');
          <% if @pets.first.user.match?(current_user) %>
            document.querySelector("#btn-like a").click();
            document.querySelector('#sweet-alert-matched').click();
          <% else %>
            window.location.href = '<%= accept_path(@pets.first.user) %>';
          <% end %>
        }
      }
    },
  });

  mySwiper.init();

  var photoSlideShow = new Swiper('.photo-slideshow', {
    init: true,
    speed: 250,
    loop: false,
    spaceBetween: 0,
    autoHeight: true, //enable auto height
    // allowTouchMove: false,
    direction: 'vertical',
    // wrapperClass: 'slideshow-wrapper',
    // pagination: {
    //   el: '.swiper-pagination',
    //   clickable: true,
    // },
    // navigation: {
    //   nextEl: '.swiper-button-next',
    //   prevEl: '.swiper-button-prev',
    // }
  });

  // photoSlideShow.init();
  // var mySwiper2 = document.querySelector('.swiper-container').swiper
    // var mySwiper2 = document.querySelector('.swiper-container').swiper
  document.querySelectorAll(".button-expand").forEach(button => {

  button.addEventListener("click", (event) => {
  document.querySelector("body").classList.toggle("expanded")
  document.querySelector("body").classList.toggle("non-scroll")
  });
  })

  document.querySelector('.show-all-button').addEventListener('click', () => {
  document.querySelector('.remaining-reviews').classList.remove('hidden')
  document.querySelector('.show-all-button').remove()
  })
</script>

app/views/pets/new.html.erb
<%= render "pets/form" %>

app/views/pets/show.html.erb
<div class="myfriends-title" id="my-pet-picture-photo">
  <h1><%= current_user.pet.name %> Pictures</h1>
</div>
<div class="button-chat" id="upload-button">Upload Photo</div>
<%= simple_form_for(@pet) do |f| %>
  <%= f.input :photos, as: :file, label: false, input_html: { multiple: true } %>
<% end %>
<div class="show-pet-card">
  <% @pet.photos.each do |photo| %>
    <div class="show-pet-card-card">
      <%=cl_image_tag(photo.key, class: "show-pet-card-images", height: 150, width:100, crop: :fill)  %>
      <div class="show-pet-card-delete">
        <%= link_to delete_image_attachment_collection_path(photo.signed_id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, class: "button-photo-delete" do %>
          <i class="fas fa-minus-square"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<script>
  const uploadButton = document.querySelector("#upload-button")
  const petPhotos = document.querySelector("#pet_photos");
  const form = document.querySelector(".edit_pet");
  petPhotos.addEventListener("change", () => form.submit())
  uploadButton.addEventListener("click", () => {
    petPhotos.click()
  });
</script>

app/views/pets/test.html.erb
<% @pet = Pet.find_by(user: pending_friends.include?(current_user))