config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'chat_rooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets do
    resources :ratings, only: [:new, :create]
  end
  resources :matches, only: [:index, :show]

  resources :chat_rooms, only: [:show] do
    resources :messages, only: [:create]
  end

  get 'my_page', to: 'users#my_page', as: :my_page
  get 'friends', to: 'users#friends', as: :friends
  get 'chats', to: 'users#chats', as: :chats
  get 'map', to: 'users#map', as: :map
  get 'users/:id/request', to: 'users#friend_request', as: :request
  get 'users/:id/accept', to: 'users#friend_accept', as: :accept
  get 'users/:id/reject', to: 'users#friend_reject', as: :reject
  get 'users/:id/accept_show', to: 'users#friend_accept_show', as: :accept_show
  # post 'chat_rooms/:chat_room_id/messages', to: 'messages#create', as: :chat_room_messages
  # get 'chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room

  get 'users/:id/remove', to: 'users#friend_remove', as: :remove

  mount ActionCable.server => "/cable"

  resources :collections do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :pet
  has_many :ratings
  has_many :messages, dependent: :destroy
  # has_many :chat_rooms, source: :chat_rooms, foreign_key: [:user_one, :user_two]
  has_one_attached :photo
  has_friendship
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  # validates :first_name, :last_name, :location, presence: true
  # exclude friend pets - current_user.friends
  # my pet - current_user.pet
  # block pets - current_user.blocked_friends
  # requested pets - current_user.pending_friends
  def excluded_friends
    pending_friends + blocked_friends + friends
  end

  def on_friendship_accepted(friendship)
    if ChatRoom.find_by(user_one: friendship.friendable, user_two: friendship.friend).nil?
    ChatRoom.create(user_one: friendship.friend, user_two: friendship.friendable, name: "#{friendship.friend.first_name}#{friendship.friendable.first_name}#{rand(0..6)}")
    end
  end

  def chat_rooms
    ChatRoom.where('user_one_id = ? OR user_two_id = ?', id, id)
  end

  def chat_room_with(user)
    chat_rooms.find_by(user_one: user)or(chat_rooms.find_by(user_two: user))
  end

  def match?(target_user)
    if self.pending_friends.include?(target_user)
      return true
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def friend_request
    target_user = User.find(params[:id])
    current_user.friend_request(target_user)

    redirect_to pets_path
  end

  # def friend_accept
  #   target_user = User.find(params[:id])
  #   target_user.accept_request(current_user)
  #   #should create and redirect to chat?
  #   #redirect_to pets_path
  #   if target_user.requested_friends.include?(current_user)
  #     current_user.accept_request(target_user)
  #   else
  #     current_user.friend_request(target_user)
  #   end
  #   # redirect_to pets_path
  # end

  # ↓↓ worked_well comment out just in case the code above has a problem
  def friend_accept
    target_user = User.find(params[:id])
    if target_user.pending_friends.include?(current_user)
      current_user.accept_request(target_user)
    else
      current_user.friend_request(target_user)
    end
    redirect_to pets_path
  end


  def friend_accept_show
    target_user = User.find(params[:id])
    current_user.accept_request(target_user)
    redirect_to pet_path(target_user.pet)
  end

  def friend_reject
    # byebug
    target_user = User.find(params[:id])
    if current_user.requested_friends.include?(target_user)
      current_user.block_friend(target_user)
    else
      target_user.friend_request(current_user)
      current_user.block_friend(target_user)
    end
    # target_user.decline_request(current_user)
    # target_user.block_friend(current_user)
    redirect_to pets_path
  end

  # def friend_remove
  #   target_user = User.find(params[:id])
  #   target_user.decline_request(current_user)
  #   # target_user.block_friend(current_user)
  #   redirect_to pets_path
  # end

  def my_page
  end

  def map
    park = User.near('Park', 1)
    @users = current_user.friends.geocoded
    @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.cl_image_path(user.pet.photos.first.key),
      }
    end
    user_marker = {
      lat: current_user.latitude,
        lng: current_user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: current_user }),
        image_url: helpers.cl_image_path(current_user.pet.photos.first.key),
    }
    @markers << user_marker
  end

  def chats
    @friends = current_user.friends.left_outer_joins(:messages).order("messages.created_at DESC").uniq
    # current_user.chat_room_with(friend).order("created_at ASC")
  end

  def friends
    @pet = current_user.pet || Pet.new
    @friends = current_user.friends.sort_by do |friend|
      friend.friendships.find_by(friend: current_user).updated_at
    end.reverse
  end
end

app/views/users/_info_window.html.erb
<h2><%= user.pet.name %></h2>
<p><%= user.first_name %></p>

app/views/users/chats.html.erb
<div class="myfriends-title">
  <h1> <%= current_user.pet.name %> Chats</h1>
</div>
<%#= cl_image_tag(current_user.friends.first.pet.photo.key, class: "avatar-chat-room") %>
<div class="chat-list">
  <%# byebug %>
  <% @friends.each do |friend| %>
    <div class="chat-room">
      <div class="chat-room-avatar">
        <%= link_to chat_room_url(current_user.chat_room_with(friend)) do %>
          <%= cl_image_tag(friend.pet.photos.first.key, class: "avatar-chat-room") %>
        <% end %>
      </div>
      <div class="chat-room-info">
        <p> <strong><%=  friend.pet.name%></strong> </p>
        <p><%= current_user.chat_room_with(friend).messages.last.try(:content)%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/friends.html.erb
<div class="myfriends-title">
  <h1><%= current_user.pet.name %>'s Friends</h1>
</div>
<div class="cards">
  <% @friends.each do |friend| %>
    <% if friend.pet %>
      <div class="card-dog-big">
        <div class="card-dog">
          <div class="card-dog-dphoto">
            <% if friend.pet.photos.attached? %>
              <%= cl_image_tag(friend.pet.photos.first.key, class: "avatar-pet") %>
            <% else %>
              <%= cl_image_tag("my_pet", class: "avatar-pet") %>
            <% end %>
          </div>
          <div class="pet-info">
            <div>
              <h5> <%= friend.pet.name %> </h5>
              <p> <%= friend.pet.breed %></p>
            </div>
            <div class="card-dog-info">
              <div class="card-dog-info-inside">
                <span><%= friend.pet.age %></span>
              </div>
              <div class="card-dog-info-inside">
                <% if friend.pet.gender == "male" %>
                  <i class="fas fa-mars"></i>
                <% else %>
                  <i class="fas fa-venus"></i>
                <% end %>
              </div>
            </div>
          </div>
          <div class="card-dog-user">
            <% if friend.photo.attached? %>
              <%= cl_image_tag(friend.photo.key, class: "avatar-bordered")%>
            <% else %>
              <%= cl_image_tag("default-avatar", class: "avatar-bordered") %>
            <% end %>
            <div class="card-dog-user-info">
              <p>Owner</p>
              <p><strong> <%= friend.first_name %></strong></p>
            </div>
            <!-- <i class="fas fa-user-slash btn reject" id="sweet-alert-demo"></i> -->
          </div>
          <div class="tab-button-chat">
            <div class="tab-button-chat-i">
              <%= link_to new_pet_rating_url(@pet), class: "button-chat" do %>
                <i class="fas fa-bone"></i> Rate
              <% end %>
            </div>
            <div class="tab-button-chat-i">
              <%= link_to chats_path, class: "button-chat" do%>
                <i class="fas fa-comment-dots "></i> Chat
              <% end %>
            </div>
            <div class="tab-button-chat-i">
              <%= link_to map_path, class: "button-chat" do %>
                <i class="fas fa-map-marker-alt"></i> Map
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/map.html.erb
<div id="map-tab">
  <div
    id="map"
    style="width: 100%;
    height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/users/my_page.html.erb
<!-- <div class="container"> -->
<% if current_user.pet %>
  <div style="height: 100vh" class="container d-flex flex-column justify-content-between">
    <div class="mp-avatar-pet">
      <% if current_user.pet.photos.attached? %>
        <%= cl_image_tag( current_user.pet.photos.first.key, class: "avatar-large", height:200, width: 200, crop: :fill)%>
      <% else %>
        <%= cl_image_tag("my_pet", class: "avatar-large", height:100, width: 100, crop: :fill) %>
      <% end %>
      <div class="back-to-home-button">
        <%= link_to root_path do  %>
          <h3> <%= current_user.pet.name %> </h3>
        <% end %>
      </div>
      <p><%= current_user.pet.breed %></p>
    </div>
    <div class="paw-photo" style="height: 420px; background: url(<%= cl_image_path("paw3_wruzvq", heigth: 300, width: 300, crop: :fill) %>) no-repeat center;">
      <div class="row" >
        <div class="col-3 col-sm-2 offset-md-2" style='margin-top: 5rem;'>
          <%= link_to friends_path, class: "btnnn" do  %>
            <i class="fas fa-users"></i>
          <% end %>
        </div>
        <div class="col-3 col-sm-2">
          <%= link_to map_path, class: "btnnn" do  %>
            <i class="fas fa-map-marked-alt"></i>
          <% end %>
        </div>
        <div class="col-3 col-sm-2">
          <%= link_to edit_user_registration_path(current_user), class: "btnnn btn2" do  %>
            <i class="fas fa-user-edit"></i>
          <% end %>
        </div>
        <div class="col-3 col-sm-2" style='margin-top: 5rem;'>
          <%= link_to edit_pet_path(current_user.pet), class: "btnnn btn3" do  %>
            <i class="fas fa-dog"></i>
          <% end %>
        </div>
        <div class="button-camera-mp">
          <%= link_to pet_path(current_user.pet) do  %>
            <i class="fas fa-camera-retro"></i>
          <% end %>
        </div>
      </div>
      <div class="d-flex justify-content-center">
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/create_pet' %>
<% end %>
<!-- </div> -->
<%#= render "shared/tabs" %>