config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'chat_rooms/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets do
    resources :ratings, only: [:new, :create]
  end
  resources :matches, only: [:index, :show]

  resources :chat_rooms, only: [:show] do
    resources :messages, only: [:create]
  end

  get 'my_page', to: 'users#my_page', as: :my_page
  get 'friends', to: 'users#friends', as: :friends
  get 'chats', to: 'users#chats', as: :chats
  get 'map', to: 'users#map', as: :map
  get 'users/:id/request', to: 'users#friend_request', as: :request
  get 'users/:id/accept', to: 'users#friend_accept', as: :accept
  get 'users/:id/reject', to: 'users#friend_reject', as: :reject
  get 'users/:id/accept_show', to: 'users#friend_accept_show', as: :accept_show
  # post 'chat_rooms/:chat_room_id/messages', to: 'messages#create', as: :chat_room_messages
  # get 'chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room

  get 'users/:id/remove', to: 'users#friend_remove', as: :remove

  mount ActionCable.server => "/cable"

  resources :collections do
    member do
      delete :delete_image_attachment
    end
  end
end

app/views/shared/_banner.html.erb
<div class="banner">
  <video src="<%= asset_url 'border.mp4' %>" autoplay="" loop="" muted="" playsinline="" class="home_video"></video>
  <!-- <div class="container">
    <div class="row">
      <div class="col-4 offset-0"> -->
  <div class="container-banner">
    <div class="banner-logo">
      <%= link_to root_path do %>
        <%= image_tag("logo.jpg", class: "logo", heigth: 500, width: 500, crop: :fill) %>
      <% end %>
    </div>
    <div class="container-banner-inner">
      <h1>Find a friend for your Pet</h1>
      <p>Make your pet happy, connect with play companions close to you</p>
      <%= link_to "Start Here!", my_page_path, class: "button-start"%>
    </div>
  </div>
  <!--     </div>
    </div>
  </div> -->
</div>

app/views/shared/_create_pet.html.erb
<div class="container-pet-create">
  <h1>Seems that you dont have a pet</h1>
  <%= link_to "Create Pet", new_pet_path(current_user.pet), class: "button-chat"  %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= cl_image_tag( "junya", width: 50, heigth: 50, crop: :fill, class: "navbar-photo") %>
    <%= cl_image_tag( "tj", width: 50, heigth: 50, crop: :fill, class: "navbar-photo") %>
    <%= cl_image_tag( "sho", width: 50, heigth: 50, crop: :fill, class: "navbar-photo") %>
    <%= cl_image_tag( "antonio", width: 50, heigth: 50, crop: :fill, class: "navbar-photo") %>
  </div>
  <div class="footer-copyright">
    Made by four magnificent people
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="200x200" href="<%= image_path 'icons/backbutton-200x200.png' %>">
<link rel="apple-touch-icon" sizes="225x225" href="<%= image_path 'icons/foward-225x225.png' %>">
<link rel="apple-touch-icon" sizes="225x225" href="<%= image_path 'icons/refresh-225x225.png' %>">

app/views/shared/_message.html.erb
<div class="message><%= user_is_messages_author ? "right" : "" %>">
  <%= image_tag message.user.avatar.url, class: "avatar" %>
  <div class="message-content"><%= message.content %></div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= cl_image_tag("woofer", heigth: 50, width: 50, crop: :fill) %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%#= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached?%>
            <%= cl_image_tag(current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false)  %>
          <% else %>
            <%= cl_image_tag("default-avatar", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Page", my_page_path, class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <button id="sweet-alert" class="dropdown-item">Log out</button>
            <%= link_to "", destroy_user_session_path, method: :delete, class: "hidden", id: "button-log" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbarv2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to my_page_path, class: "navbar-icon" do %>
    <i class="fas fa-user fa-2x"></i>
  <% end %>
  <%= link_to pets_path do %>
    <%= image_tag("logo.jpg", class: "logo2", heigth: 500, width: 500, crop: :fill) %>
  <% end %>
  <%= link_to chats_path, class: "navbar-icon" do %>
    <i class="fas fa-comment-dots fa-2x"></i>
  <% end %>
</div>

app/views/shared/_tabs.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <%= link_to "My Matches", '#match', class: "nav-link active", id: "match-tab", 'data-toggle': "tab", role: "tab", 'aria-controls': "matches", 'aria-selected': "true"  %>
  </li>

  <li class="nav-item">
    <%= link_to "Add or Edit a Pet", '#create', class: "nav-link", id: "create-tab", 'data-toggle': "tab", role: "tab", 'aria-controls': "create", 'aria-selected': "false"  %>
  </li>

  <li class="nav-item">
    <%= link_to "Edit Profile", '#edit', class: "nav-link", id: "edit-tab", 'data-toggle': "tab", role: "tab", 'aria-controls': "edit", 'aria-selected': "false"  %>
  </li>

  <li class="nav-item">
    <%= link_to "Friends Close To You", '#map-box', class: "nav-link", id: "map-tab", 'data-toggle': "tab", role: "tab", 'aria-controls': "map", 'aria-selected': "false"  %>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="match" role="tabpanel" aria-labelledby="matches-tab">
    <div class="cards">
      <% @friends.each do |friend| %>
        <% if friend.pet %>
          <div class="card-dog-big">
            <div class="card-dog">
              <div class="card-dog-dphoto">
                <% if friend.pet.photo.attached? %>
                  <%= cl_image_tag(friend.pet.photo.key, class: "avatar-pet") %>
                <% else %>
                  <%= cl_image_tag("my_pet", class: "avatar-pet") %>
                <% end %>
              </div>
              <div class="pet-info">
                <h5> <%= friend.pet.name %> </h5>
                <p> <%= friend.pet.breed %></p>
              </div>
              <div class="card-dog-info">
                <div class="card-dog-info-inside">
                  <span><%= friend.pet.age %></span>
                </div>
                <div class="card-dog-info-inside">
                  <% if friend.pet.gender == "male" %>
                    <i class="fas fa-mars"></i>
                  <% else %>
                    <i class="fas fa-venus"></i>
                  <% end %>
                </div>
              </div>
              <div class="card-dog-user">
                <% if friend.photo.attached? %>
                  <%= cl_image_tag(friend.photo.key, class: "avatar-bordered")%>
                <% else %>
                  <%= cl_image_tag("default-avatar", class: "avatar-bordered") %>
                <% end %>
                <div class="card-dog-user-info">
                  <p>Owner</p>
                  <p><strong> <%= friend.first_name %></strong></p>
                </div>
                  <i class="fas fa-user-slash btn reject" id="sweet-alert-demo"></i>
                  <%= link_to "#", reject_path(friend), id: "block-friend" %>
              </div>
              <div class="tab-button-chat">
                <%= link_to "Chat", chat_room_url(current_user.chat_room_with(friend)), class: "btn btn-primary"  %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="create" role="tabpanel" aria-labelledby="create-tab">
    <%= render "pets/form" %>
  </div>
  <!-- <div class="tab-pane fade" id="edit" role="tabpanel" aria-labelledby="edit-tab">
  <p>edit</p>
  </div> -->
  <div class="tab-pane fade" id="edit" role="tabpanel" aria-labelledby="edit-tab">
    <%#= render "devise/registrations/form" %>
    <p>next summer</p>
  </div>
  <div class="tab-pane fade" style="width: 100%" id="map-box" role="tabpanel" aria-labelledby="map-tab">
    <%#= render "devise/registrations/form" %>
    <%= render "users/map" %>
  </div>
</div>